Fill Mode added
kBlaszczyk/game_of_life pull request #14
Opened 2020-11-19 20:52 UTC by HannahRKent

2020-12-08 16:07 UTC, kBlaszczyk requested changes
I think the application crashes when the filling process reaches the board limits.
Try to fill after clearing out everything.

2020-12-08 16:07 UTC, kBlaszczyk commented on src/main/java/de/orchound/gameoflife/view/Painter.java
> +		if (fillMode) {
The painting algorithms shouldn't be implemented in the same class.
Create a `Painter` interface and then a `TogglePainter` for the original implementation and a `FillPainter` for filling in cells.
The painters should be organized in the `Applet` and selected if an appropriate button is being clicked.

2020-12-17 15:49 UTC, kBlaszczyk requested changes

2020-12-17 15:49 UTC, kBlaszczyk commented on src/main/java/de/orchound/gameoflife/GameOfLifeApplet.java
> +	// private PainterPicker painterPicker;
remove line
```suggestion
```

2020-12-17 15:49 UTC, kBlaszczyk commented on src/main/java/de/orchound/gameoflife/GameOfLifeApplet.java
> +		System.out.println("fill mode");
remove the debug logs
```suggestion
```

2020-12-17 15:49 UTC, kBlaszczyk commented on src/main/java/de/orchound/gameoflife/GameOfLifeApplet.java
> +		System.out.println("toggle mode");
remove the debug logs
```suggestion
```

2020-12-17 15:49 UTC, kBlaszczyk commented on src/main/java/de/orchound/gameoflife/model/Game.java
> +			notifyBoardDataObservers();
The point was to not notify the observers when setting a cell silently, right?
```suggestion
```

2020-12-17 15:49 UTC, kBlaszczyk commented on src/main/java/de/orchound/gameoflife/model/Game.java
> +	public boolean cellInBoardRange(Vector2ic cell) {
The board range validation is done internally when setting a cell.
Make this private again and remove the method call from the `FillPainter`.

2020-12-17 15:49 UTC, kBlaszczyk commented on src/main/java/de/orchound/gameoflife/painting/FillPainter.java
> +			fillCells(new Vector2i(cell.x(), cell.y()-1));
Fix operator spaces.
```suggestion
			fillCells(new Vector2i(cell.x(), cell.y() + 1));
			fillCells(new Vector2i(cell.x(), cell.y() - 1));
```

2020-12-17 15:49 UTC, kBlaszczyk commented on src/main/java/de/orchound/gameoflife/view/Painter.java
>  public class Painter {
You should be able to remove the `Painter` class now.

2020-12-17 15:49 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/painting/FillPainterTest.java
> +			game.toggleCell(new Vector2i(i, 2));
Using `setCell()` here and below is more explicit.

2020-12-17 15:49 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/painting/TogglePainterTest.java
> +		game.clear();
Redundant clear call.
```suggestion
```

2020-12-17 15:49 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/painting/TogglePainterTest.java
> +		for (int i = 0; i <= game.getSize().x(); i++) {
This test only verifies the setting of a cell, not the actual toggle logic.
Maybe just toggle an entire random board and then verify that every cell changed status.

2020-12-17 15:49 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/view/BoardViewTest.java
> +	private final Painter painter = new TogglePainter(game);
No need for this member in this test.

2020-12-17 15:49 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/view/PainterTest.java
> +//package de.orchound.gameoflife.view;
File can be removed

2020-12-22 03:44 UTC, HannahRKent commented on src/main/java/de/orchound/gameoflife/model/Game.java
> +	public boolean cellInBoardRange(Vector2ic cell) {
Removing the method call causes my tests to fail

2020-12-22 04:19 UTC, HannahRKent commented on src/test/java/de/orchound/gameoflife/painting/TogglePainterTest.java
> +		for (int i = 0; i <= game.getSize().x(); i++) {
Wasn't sure what you meant, I don't think the togglepainter actually uses toggleCell.  Maybe we have bad naming?  Anyway I made the test better

2021-01-05 16:05 UTC, kBlaszczyk requested changes

2021-01-05 16:05 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/view/BoardViewTest.java
> +		boardView = new BoardView(game, sketch, boardRenderer, new TogglePainter(game));
Using a `Painter` mock here would be nice.

2021-01-05 16:05 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/painting/FillPainterTest.java
> +		game.clear();
Remove redundant `clear()` call.
```suggestion
```

2021-01-05 16:05 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/painting/TogglePainterTest.java
> +	void testPaint() {
This test could be better. Try implementing the following scenario.
```
oxo    xxx
xox => ooo
^
```
The painting is started on the first cell for both lines.
(each line is representing a single painting process, consider creating two test methods)

2021-01-05 16:05 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/painting/FillPainterTest.java
> +	void testPaint() {
Please implement two test methods `testFillBoard()` and `testFillSquare()`.
The former simply fill paints any cell of an empty board and verifies that the entire board is set.
The latter could paint a 4x4 square on the 6x6 board and then fill paint that square. (Then verifying that only the square and its' content was set)

2021-02-01 18:07 UTC, kBlaszczyk requested changes

2021-02-01 18:07 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/painting/FillPainterTest.java
> +		game.setCell(new Vector2i(3, 4), true);
Simplify the square initialization like this:
```suggestion
for (int i = 1; i < 5; i++) {
	game.setCell(new Vector2i(i, 1), true);
	game.setCell(new Vector2i(1, i), true);
	game.setCell(new Vector2i(4, i), true);
	game.setCell(new Vector2i(i, 4), true);
}
```

2021-02-01 18:07 UTC, kBlaszczyk commented on src/test/java/de/orchound/gameoflife/painting/FillPainterTest.java
> +		}
Verifying the immediate surroundings of the square can also be simplified like this:
```suggestion
for (int i = 0; i < 6; i++) {
	assertFalse(game.getCellStatus(new Vector2i(0, i)));
	assertFalse(game.getCellStatus(new Vector2i(i, 0)));
	assertFalse(game.getCellStatus(new Vector2i(5, i)));
	assertFalse(game.getCellStatus(new Vector2i(i, 5)));
}
```

2021-02-01 21:07 UTC, kBlaszczyk approved these changes

2021-02-01 21:08 UTC, merged